plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0' // Güvenli ve kararlı sürüme çekildi
    id 'io.spring.dependency-management' version '1.1.5' // Boot 3.3.0 ile uyumlu sürüm
}


group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'IKSystem'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    runtimeOnly 'org.postgresql:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation('org.springframework.boot:spring-boot-starter-validation')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
    implementation('org.springframework.boot:spring-boot-starter-mail')
    implementation('org.springframework.boot:spring-boot-starter-security')




    // Ana Kod için Doğru Lombok Tanımları
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'

    // Test Kodları için Doğru Lombok Tanımları
    testCompileOnly 'org.projectlombok:lombok:1.18.28'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.28'
}


tasks.named('test') {
    useJUnitPlatform()
}
