spring.application.name=IKSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/IK_SYSTEM
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


